services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: dabstep-agents:latest
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./runs:/workspace/runs
    env_file:
      - .env
    ports:
      - "6006:6006"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]
